version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: crud_backend_postgres
    environment:
      POSTGRES_DB: crud_backend
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - crud_network

  app:
    build: .
    container_name: crud_backend_app
    ports:
      - '3000:3000'
    environment:
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_USER: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_NAME: crud_backend
      JWT_SECRET: your-super-secret-jwt-key-change-in-production
      JWT_EXPIRATION: 1d
      PORT: 3000
    depends_on:
      - postgres
    volumes:
      - ./uploads:/app/uploads
    networks:
      - crud_network

  frontend:
    build:
      context: ../crud_frontend
    container_name: crud_frontend_app
    ports:
      - '4200:80'
    depends_on:
      - app
    networks:
      - crud_network

volumes:
  pgdata:

networks:
  crud_network:
    driver: bridge
